## Numpy

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
# Reshaping

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
print(arr2)

[1 2 3 4 5]


In [6]:
# 2d array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [7]:
#in-built array functions

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
## Attributes of Numpy Arrays

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape)
print("Number of dimension:",arr.ndim)
print("size(number of elements):", arr.size)
print("data type:",arr.dtype)
print("item size:",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
size(number of elements): 6
data type: int64
item size: 8


In [15]:
## numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print('addition:',arr1 + arr2)
print('substraction:',arr1 - arr2)
print('multiplication:', arr1 * arr2)
print('division:',arr2 / arr1)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [10. 10. 10. 10. 10.]


In [16]:
## universal function

arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [17]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('array:\n',arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [19]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [20]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [21]:
## Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [22]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [24]:
## statistical concepts -- Morrmalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print('Normalized Data:',normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [29]:
data = np.array([2,3,4,5,6])

mean = np.mean(data)
print('mean:',mean)

median = np.median(data)
print('median:',median)

std_dev = np.std(data)
print('standard deviation:',std_dev)

variance = np.var(data)
print('variance:',variance)

mean: 4.0
median: 4.0
standard deviation: 1.4142135623730951
variance: 2.0


In [28]:
## logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >= 5) & (data <=8)]

array([5, 6, 7, 8])